apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: thanos-watchdog-rules
  namespace: monitoring
  labels:
    lnrs.io/k8s-platform: "true"
    lnrs.io/monitoring-platform: "true"
    lnrs.io/thanos-rule: "true"
spec:
  groups:
    - name: thanos-watchdog.rules
      rules:
        - alert: Watchdog
          annotations:
            description: >
              This is an alert meant to ensure that the entire alerting pipeline
              is functional.

              This alert is always firing, therefore it should always be firing
              in Alertmanager

              and always fire against a receiver. There are integrations with
              various notification

              mechanisms that send a notification when this alert is not firing.
              For example the

              "DeadMansSnitch" integration in PagerDuty.
            runbook_url: >-
              https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-watchdog
            summary: >-
              An alert that should always be firing to certify that Alertmanager
              is working properly.
          expr: vector(1)
          labels:
            severity: none
